name: Unpash CI
on: [push]
jobs:
  Build:
    runs-on: ubuntu-18.04
    steps:
	- uses: actions/checkout@v2
    - run: docker build -t docker-rdkit:${{github.sha}} .
    - name: Push to ECR
      id: prod-ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-west-1
        image: docker-rkdit:${{github.sha}}
